title = "Alex Nuttall"
baseURL = "https://thick-hollins.netlify.app"
theme ="hugo-theme-basic"
languageCode = "en"
googleAnalytics = "UA-XXXXXXXXX-X"
enableEmoji = true 
copyright = "© 2021"
description = "A software developer's personal site"
pygmentsUseClassic=false

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[params]
  titleEmoji = ":laptop:"
  twitter = "thick_hollins"

[Permalinks]
  post = "post/:slug"
  project = "project/:slug"

[[params.menu]]
  name = "blog"
  url = "post/"

[[params.menu]]
  name = "projects"
  url = "project/"
  
[[params.menu]]
  name = "about"
  url = "about/"
  

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true

